# ───────── Ruff ─────────
[tool.ruff]
exclude = ["backend/migrations/*"]

[tool.ruff.lint]
select = ["E", "F", "B"]
ignore  = ["E501"]

# ───────── Mypy ─────────
[tool.mypy]
python_version        = "3.11"
ignore_missing_imports = true
exclude               = ["backend/migrations/"]
disable_error_code    = ["attr-defined", "call-arg", "union-attr"]
