name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    # ====== Install dependencies (prod + dev) ======
    - name: Install frontend dependencies
      working-directory: frontend
      # отключаем прод-режим и говорим брать devDeps
      run: |
        npm ci --include=dev
      env:
        CI: ""                  # ← переопределяем
        NPM_CONFIG_PRODUCTION: "false"
        NODE_ENV: "development"


    # ====== Playwright browsers ======
    - name: Install Playwright browsers
      working-directory: frontend
      run: npx playwright install --with-deps

    # ====== Run tests ======
    - name: Run Playwright tests
      working-directory: frontend
      run: npx playwright test --reporter=line

    # ====== Сохранить html-отчёт (если нужен) ======
    - name: Upload Playwright report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
