# .github/workflows/playwright.yml
name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      # Устанавливаем и prod, и dev зависимости
      - name: Install frontend deps
        working-directory: frontend
        env:
          # гарантируем установку devDependencies
          NPM_CONFIG_PRODUCTION: "false"
        run: npm ci

      # Устанавливаем браузеры для Playwright
      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps

      # Запускаем E2E-тесты
      - name: Run Playwright tests
        working-directory: frontend
        run: npx playwright test --reporter=line

      # (опционально) собираем HTML-отчёт
      - name: Upload Playwright report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
