# .github/workflows/playwright.yml
name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          # кэшируем именно frontend/package-lock.json
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies (frontend)
        working-directory: frontend
        run: npm ci

      - name: Install Playwright browsers
        working-directory: frontend
        # --with-deps ставит системные зависимости, нужные в Ubuntu-runner’е
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: frontend
        # конфиг и тесты уже в этом каталоге
        run: npx playwright test --config=playwright.config.ts

      # если нужны отчёты — выгрузим независимо от статуса (always)
      - name: Upload Playwright report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
          retention-days: 30
