# .github/workflows/playwright.yml
name: Playwright Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      # ====== install prod+dev deps ======
      - name: Install frontend deps
        working-directory: frontend
        env:
          NPM_CONFIG_PRODUCTION: "false"
        run: npm ci

      # ====== Playwright browsers ======
      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps

      # ====== run tests ======
      - name: Run Playwright tests
        working-directory: frontend
        run: npx playwright test --reporter=line

      # ====== attach HTML-report (всегда) ======
      - name: Upload Playwright report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
