name: Playwright Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    # ====== install dependencies (dev + prod) ======
    - name: Install frontend deps
      working-directory: frontend
      env:
        # сбрасываем флаг, который GitHub задаёт автоматически
        CI: ""
        # отключаем прод-режим npm
        NPM_CONFIG_PRODUCTION: "false"
      run: |
        npm install --no-audit --progress=false

    # ====== Playwright browsers ======
    - name: Install Playwright browsers
      working-directory: frontend
      run: npx playwright install --with-deps

    # ====== run tests ======
    - name: Run Playwright tests
      working-directory: frontend
      run: npx playwright test --reporter=line

    # ====== attach HTML-report (всегда) ======
    - name: Upload Playwright report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
