name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    # --- ВСЕ дальнейшие шаги выполняем внутри ./frontend ---
    - name: Install dependencies (prod + dev)
      run: npm ci --include=dev
      working-directory: frontend
      env:
        NODE_ENV: ""


    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: frontend

    - name: Run Playwright tests
      run: npx playwright test
      working-directory: frontend

    - name: Upload Playwright report
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
